//! writ: a local daemon that mints short-lived, per-request-scoped
//! credentials for agents and records every grant in an append-only
//! audit log.
//!
//! See `docs/design/broker.md` for the architecture overview.

pub mod agent_run;
#[cfg(feature = "host")]
pub mod agent_vm_daemon;
#[cfg(feature = "host")]
pub mod agent_vm_firewall;
#[cfg(feature = "host")]
pub mod agent_vm_lifecycle;
#[cfg(feature = "host")]
pub mod audit;
pub(crate) use writ_core::bearer;
#[cfg(feature = "host")]
pub mod boot_reconcile;
#[cfg(feature = "host")]
pub(crate) mod clean_git;
#[cfg(feature = "host")]
pub mod cli;
#[cfg(feature = "host")]
pub mod config;
pub use writ_core::core;
#[cfg(feature = "host")]
pub mod flake_lock;
#[cfg(feature = "host")]
pub mod flake_provision;
#[cfg(feature = "host")]
pub mod git_commit_sign;
#[cfg(feature = "host")]
pub mod git_push_approve;
#[cfg(feature = "host")]
pub mod git_push_promote;
#[cfg(feature = "host")]
pub mod git_push_replay;
#[cfg(feature = "host")]
pub(crate) mod git_push_replay_object_parse;
#[cfg(feature = "host")]
pub mod git_push_replay_object_source;
#[cfg(feature = "host")]
pub mod git_push_replay_walker;
#[cfg(feature = "host")]
pub mod git_push_staging;
#[cfg(feature = "host")]
pub mod github;
#[cfg(feature = "host")]
pub mod github_git_db;
#[cfg(feature = "host")]
pub mod nix_cache;
#[cfg(feature = "host")]
pub mod notes_repo;
#[cfg(feature = "host")]
pub mod openai_chatgpt_auth;
#[cfg(feature = "host")]
pub mod policy;
pub use writ_core::process_spawn;
#[cfg(feature = "host")]
pub(crate) mod process_supervisor;
#[cfg(feature = "host")]
pub mod protocol;
#[cfg(feature = "host")]
pub mod run_envelope;
#[cfg(feature = "host")]
pub mod run_verify;
#[cfg(feature = "host")]
pub mod secret;
#[cfg(feature = "host")]
pub mod server;
#[cfg(feature = "host")]
pub mod signing;
pub use writ_core::telemetry;
#[cfg(feature = "host")]
pub mod ui_http;
#[cfg(feature = "vm-client")]
pub mod vm_client;
#[cfg(feature = "vm-client")]
pub use writ_vm_git as vm_git;
#[cfg(feature = "host")]
pub mod vm_git_bundle;
#[cfg(feature = "host")]
pub mod vm_git_mirror_cache;
#[cfg(feature = "host")]
pub mod vm_http;
#[cfg(feature = "host")]
pub mod writ_client;
